global using Microsoft.EntityFrameworkCore;
global using System.ComponentModel.DataAnnotations;
global using Microsoft.AspNetCore.Mvc.Rendering;
global using GameZone.Services.Implementation;
global using GameZone.Services.Interfaces;
global using GameZone.Data;
global using GameZone.Models;
global using Microsoft.Extensions.Options;
global using GameZone.Configurations;
